sudo: true
language: c
compiler:
    - gcc
os:
    - linux
before_install:
        - wget http://dist.schmorp.de/libev/Attic/libev-4.15.tar.gz
        - tar -xzvf libev-4.15.tar.gz
        - cd libev-4.15 && ./configure --prefix=/usr/lib && make && sudo make install
        - cd ..
install:
        - git clone https://github.com/regrant/portals4.git
        - ./autogen.sh
        - ./configure --prefix=$HOME --with-libev=/usr/lib/ --enable-zero-mrs --enable-reliable-udp
        - make -j2
        - make install
script:
        - make check
